# 8. 예외 처리하기

- 예외란 보통 처리하지 못한 에러를 가리킨다.
- 이러한 예외는 실행 중인 노드 프로세스를 멈추게 한다.
- 노드는 메인 스레드가 하나 뿐이므로 소중하게 보호해야 한다.

```js
// error1.js
setInterval(() => {
    console.log('시작');
    try {
        throw new Error('서버를 고장내주마!');
    } catch (err) {
        console.error(err);
    }
}, 1000);
```

```zsh
$ node error1
시작
Error: 서버를 고장내주마!
# ...
시작
Error: 서버를 고장내주마!
# ...
# ...반복...
```

- 에러는 발생하지만 `try/catch`로 잡을 수 있고 `setInterval`도 계속 실행된다.

```js
// error2.js
const fs = require('fs');

setInterval(() => {
    fs.unlink('./abcdefg.js', err => {
        if (err) {
            console.error(err);
        }
    });
}, 1000);
```

```zsh
$ node error2
[Error: ENOENT: no such file or directory, unlink './abcdefg.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: './abcdefg.js'
}
[Error: ENOENT: no such file or directory, unlink './abcdefg.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: './abcdefg.js'
}
# ...반복...
```

- 존재하지 않는 파일을 지우므로 에러가 발생한다.
- 하지만 노드 내장 모듈의 에러는 실행 중인 프로세스를 멈추지 않는다.
- 에러 로그를 기록하고 나중에 원인을 찾아 수정하면 된다.

```js
// error3.js
const fs = require('fs').promises;

setInterval(() => {
    fs.unlink('./abcdefg.js');
}, 1000);
```

```zsh
$ node error3
(node:4250) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, unlink './abcdefg.js'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4250) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4250) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
# ...반복...
```

- 프로미스의 에러는 `catch`하지 않아도 알아서 처리한다.
- 따라서 프로미스를 사용할 때는 항상 `catch`를 붙여주는 것을 권장한다.

```js
// error4.js
process.on('uncaughtException', err => {
    console.error('예기치 못한 에러', err);
});

setInterval(() => {
    throw new Error('서버를 고장내주마!');
}, 1000);

setTimeout(() => {
    console.log('실행됩니다');
}, 2000);
```

```zsh
$ node error4
예기치 못한 에러 Error: 서버를 고장내주마!
# ...
실행됩니다
예기치 못한 에러 Error: 서버를 고장내주마!
예기치 못한 에러 Error: 서버를 고장내주마!
# ...반복...
```

- 위 코드는 예측이 불가능한 에러를 처리하는 방법을 알아보기 위한 코드다.
- 처리하지 못한 에러가 발생했을 때 이벤트 리스너가 실행되고 프로세스가 유지된다.
    - 만약 이 부분이 없다면 `setTimeout`은 실행되지 않았을 것이다.
- `uncaughtException` 이벤트 리스너가 연결되어 프로세스가 멈추지 않았다.
- 노드 공식 문서에서는 `uncaughtException` 이벤트는 최후의 수단으로 사용할 것을 명시하고 있다.
    - 이는 다음 동작이 제대로 동작하는지 보증하지 못한다.
    - 즉, 복구 작업 코드를 넣어두었더라도 그것이 동작하는지 확신할 수 없다.
- 따라서 `uncaughtException`은 에러 내용을 기록하고 프로세스를 종료하도록 사용하는 것이 좋다.
- 에러 발생 시 철저히 기록하는 습관을 들여, 주기적으로 확인하며 보완해나가야 한다.

## 8.1 자주 발생하는 에러들

- `node:command not found`
    - 노드가 설치되어 있지 않거나, 설치되었으나 환경 변수가 제대로 설정되지 않았다.
- `ReferenceError: 모듈 is not defined`
    - 모듈을 `require`했는지 확인한다.
- `Error: Cannot find module 모듈명`
    - 해당 모듈을 `require`했지만 설치하지 않았다.
    - `npm install`을 통해 설치하도록 한다.
- `Error: Can't set headers after they are sent`
    - 요청에 대한 응답을 보낼 때 두 번 이상 보냈다.
- `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`
    - 코드를 실행할 때 메모리가 부족하여 스크립트가 정상 작동하지 않는 경우다.
    - `node --max-old-space-size=4096 파일명`과 같은 명령어로 늘린다.
- `UnhandledPromoiseRejectionWarning: Unhandled promise rejection`
    - 프로미스 사용 시 `catch` 메서드를 사용하지 않았을 경우다.
    - 항상 `catch`를 사용해 에러 상황을 대비하도록 한다.
- `EADDRINUSE 포트 번호`
    - 해당 포트 번호에 이미 다르프로세스가 연결되어 있다.
- `EACCES 또는 EPERM`
    - 노드가 작업을 수행하는 데 권한이 충분치 않다.
- `EJSONPARSE`
    - `package.json` 등의 JSON 파일에 문법 오류가 있을 경우다.
- `ECONNREFUSED`
    - 요청을 보냈으나 연결이 성립하지 않을 때 발생한다.
    - 요청을 받는 서버의 주소가 올바른지 꺼져 있진 않은지 확인한다.
- `ETARGET`
    - `package.json`에 기록한 패키지 버전이 존재하지 않을 때 발생한다.
- `ETIMEOUT`
    - 요청을 보냈으나 응답이 일정 시간 내에 오지 않을 때 발생한다.
- `ENOENT: no such file or directory`
    - 지정한 폴더나 파일이 존재하지 않는 경우다.

-----
[HOME](./index.md)